CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(64) NOT NULL,
    name VARCHAR(100) NOT NULL,
    category VARCHAR(32) NOT NULL,
    description VARCHAR(2000),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_products_code UNIQUE (code),
    CONSTRAINT ck_products_code CHECK (code ~ '^[A-Z0-9_]+$'),
    CONSTRAINT ck_products_name CHECK (name = btrim(name) AND name !~ '^[[:space:]]*$'),
    CONSTRAINT ck_products_category CHECK (category IN ('INTERNET', 'PHONE', 'WIFI', 'IPTV', 'SECURITY', 'ETC'))
);
